name: PR Auto Labeler

on:
  workflow_call:
    inputs:
      enabled_rules:
        description: 'List of rule names to enable (JSON array). All rules disabled by default. Example: ["frontend-ui", "env-variables"]'
        required: false
        type: string
        default: '[]'
      enabled_labels:
        description: 'List of specific labels to apply (JSON array). If empty, all labels from enabled rules are applied. Example: ["ui-change", "env-change"]'
        required: false
        type: string
        default: '[]'
      label_overrides:
        description: 'Custom label names to override defaults (JSON)'
        required: false
        type: string
        default: '{}'
      large_pr_threshold:
        description: 'Number of changed lines considered a large PR'
        required: false
        type: number
        default: 500
      enable_debug:
        description: 'Enable debug logs in workflow output'
        required: false
        type: boolean
        default: false
      skip_labels:
        description: 'Labels to skip applying (JSON array)'
        required: false
        type: string
        default: '[]'

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Analyze changes and apply labels
        uses: actions/github-script@v7
        env:
          ENABLED_RULES: ${{ inputs.enabled_rules }}
          ENABLED_LABELS: ${{ inputs.enabled_labels }}
          ENABLE_DEBUG: ${{ inputs.enable_debug }}
          LABEL_OVERRIDES: ${{ inputs.label_overrides }}
          SKIP_LABELS: ${{ inputs.skip_labels }}
          LARGE_PR_THRESHOLD: ${{ inputs.large_pr_threshold }}
        with:
          script: |
            const workflowScript = require('./src/workflow-script.js');
            await workflowScript({ github, context, core });

